// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPI.DatabaseAccess;

namespace TaskAPI.DatabaseAccess.Migrations
{
    [DbContext(typeof(TodoDBContext))]
    [Migration("20210816120244_addedAnnotaions")]
    partial class addedAnnotaions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressNo = "No 260/8",
                            City = "Hungama",
                            FullName = "Lahiru Madushanka",
                            Street = "Ginigallanda"
                        },
                        new
                        {
                            Id = 2,
                            AddressNo = "No 300/8",
                            City = "Doranagoda",
                            FullName = "Manoshi Ramanayake",
                            Street = "Kelum Uyana"
                        },
                        new
                        {
                            Id = 3,
                            AddressNo = "No 255/4",
                            City = "Galle",
                            FullName = "Nansara Piyumal",
                            Street = "Watareka"
                        },
                        new
                        {
                            Id = 4,
                            AddressNo = "No 27/2",
                            City = "deldeniya",
                            FullName = "Nimal Premarathne",
                            Street = "udapita"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Created = new DateTime(2021, 8, 16, 17, 32, 43, 206, DateTimeKind.Local).AddTicks(5824),
                            Description = "Get some text books for school",
                            Due = new DateTime(2021, 8, 21, 17, 32, 43, 207, DateTimeKind.Local).AddTicks(3164),
                            Status = 0,
                            Title = "Get books for School - DB "
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Created = new DateTime(2021, 8, 16, 17, 32, 43, 207, DateTimeKind.Local).AddTicks(4784),
                            Description = "Get vegetable for week",
                            Due = new DateTime(2021, 8, 18, 17, 32, 43, 207, DateTimeKind.Local).AddTicks(4792),
                            Status = 0,
                            Title = "Get vegetable"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Created = new DateTime(2021, 8, 16, 17, 32, 43, 207, DateTimeKind.Local).AddTicks(4805),
                            Description = "Water all the plants quickly",
                            Due = new DateTime(2021, 8, 17, 17, 32, 43, 207, DateTimeKind.Local).AddTicks(4806),
                            Status = 0,
                            Title = "Water the plants"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.HasOne("TaskAPI.Models.Author", "Author")
                        .WithMany("Todos")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TaskAPI.Models.Author", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
